CREATE TABLE `FEED` (
	`id` INTEGER PRIMARY KEY AUTOINCREMENT,
	`url` VARCHAR(2048) NULL,
	`title` VARCHAR(2048) NULL,
	`created` DATE NOT NULL
);

CREATE TABLE `ENTRY` (
	`id` VARCHAR(2048) NOT NULL PRIMARY KEY,
	`url` VARCHAR(2048) NOT NULL,
	`site` VARCHAR(2048) NULL,
	`title` VARCHAR(2048) NULL,
	`content` VARCHAR(4096) NOT NULL,
	`created` DATE NOT NULL
);
